'use strict'

const { randomUUID } = require('crypto')
const { getPool } = require('../../../db/pool')
const accountsRepo = require('../../accounts/repo')
const categoriesRepo = require('../../categories/repo')
const txnRepo = require('../../transactions/repo')
const recurringRepo = require('../../recurring/repo')
const repo = require('../repo')

const pool = getPool()

afterAll(async () => {
  await pool.end()
})

describe('insights repo', () => {
  let accountId
  let categoryId
  let ruleId
  let txnIds

  beforeEach(async () => {
    accountId = randomUUID()
    categoryId = randomUUID()
    ruleId = randomUUID()
    txnIds = []
    await accountsRepo.create(pool, { id: accountId, name: 'Insights Test Account' })
    await categoriesRepo.create(pool, { id: categoryId, name: `Insights Test Category ${categoryId}` })
  })

  afterEach(async () => {
    await pool.query('DELETE FROM recurring_runs WHERE rule_id = ?', [ruleId])
    for (const id of txnIds) {
      await pool.query('DELETE FROM transactions WHERE id = ?', [id])
    }
    await pool.query('DELETE FROM recurring_rules WHERE id = ?', [ruleId])
    await pool.query('DELETE FROM accounts WHERE id = ?', [accountId])
    await pool.query('DELETE FROM categories WHERE id = ?', [categoryId])
  })

  async function makeTxn(type, amount, txnDate, extra = {}) {
    const id = randomUUID()
    txnIds.push(id)
    await txnRepo.create(pool, {
      id,
      type,
      amount,
      txnDate,
      updatedAt: '2033-01-10 09:00:00',
      ...(type === 'expense' ? { categoryId, accountId } : { accountId }),
      ...extra,
    })
    return id
  }

  // Mark a transaction as recurring-generated by wiring a recurring_runs row.
  async function markRecurring(txnId, runDate) {
    await recurringRepo.create(pool, {
      id: ruleId,
      type: 'expense',
      amount: 1,
      accountId,
      intervalUnit: 'month',
      intervalCount: 1,
      nextRunDate: runDate,
    })
    await pool.query('INSERT INTO recurring_runs (rule_id, run_date, transaction_id) VALUES (?, ?, ?)', [
      ruleId,
      runDate,
      txnId,
    ])
  }

  describe('actualsToDate', () => {
    it('splits expense into recurring and discretionary, sums income', async () => {
      await makeTxn('income', 200000, '2033-01-01')
      await makeTxn('expense', 30000, '2033-01-05') // discretionary
      const rentId = await makeTxn('expense', 15000, '2033-01-03')
      await markRecurring(rentId, '2033-01-03')
      await makeTxn('expense', 9999, '2033-01-25') // after throughDate, excluded

      const a = await repo.actualsToDate(pool, '2033-01', '2033-01-10')
      expect(a.income).toBe(200000)
      expect(a.expense).toBe(45000)
      expect(a.discretionary).toBe(30000)
    })

    it('returns zeros for an empty window', async () => {
      const a = await repo.actualsToDate(pool, '2044-06', '2044-06-10')
      expect(a).toEqual({ income: 0, expense: 0, discretionary: 0 })
    })
  })

  describe('categoryHistory', () => {
    it('reports current-month-to-date spend and trailing total per category', async () => {
      await makeTxn('expense', 12000, '2033-05-04') // current month, to date
      await makeTxn('expense', 3000, '2033-05-20') // current month, after throughDate
      await makeTxn('expense', 8000, '2033-04-10') // previous month (in trailing window)
      await makeTxn('expense', 4000, '2033-03-10') // previous month (in trailing window)

      const rows = await repo.categoryHistory(pool, '2033-05', '2033-05-10', 3)
      const row = rows.find((r) => r.category_id === categoryId)
      expect(Number(row.current_spent)).toBe(12000)
      expect(Number(row.prev_total)).toBe(12000) // 8000 + 4000
    })
  })

  describe('budgetStatus', () => {
    let budgetId
    afterEach(async () => {
      if (budgetId) await pool.query('DELETE FROM budgets WHERE id = ?', [budgetId])
      budgetId = undefined
    })

    it('returns limit + month-to-date spend + name per active budget', async () => {
      budgetId = randomUUID()
      await pool.query('INSERT INTO budgets (id, category_id, limit_amount) VALUES (?, ?, ?)', [
        budgetId,
        categoryId,
        100000,
      ])
      await makeTxn('expense', 30000, '2033-10-04')
      await makeTxn('expense', 20000, '2033-10-09')
      await makeTxn('expense', 9999, '2033-10-25') // after throughDate, excluded

      const rows = await repo.budgetStatus(pool, '2033-10', '2033-10-10')
      const row = rows.find((r) => r.category_id === categoryId)
      expect(Number(row.limit)).toBe(100000)
      expect(Number(row.spent)).toBe(50000)
      expect(row.name).toBeTruthy()
    })
  })

  describe('categoryComparison', () => {
    it('returns current, previous-month, and trailing-average totals per category', async () => {
      await makeTxn('expense', 10000, '2033-09-05') // current
      await makeTxn('expense', 6000, '2033-08-05') // last month
      await makeTxn('expense', 3000, '2033-07-05') // trailing

      const rows = await repo.categoryComparison(pool, '2033-09', 3)
      const row = rows.find((r) => r.category_id === categoryId)
      expect(Number(row.current_total)).toBe(10000)
      expect(Number(row.last_total)).toBe(6000)
      expect(Number(row.prev_total)).toBe(9000) // 6000 + 3000 over previous 3 months
    })
  })
})
