'use strict'

const { monthRange } = require('../../lib/dateRange')

// First day of the month `n` months before `month` (YYYY-MM), as a DATE
// string. Used for trailing-window range bounds.
function monthStartBefore(month, n) {
  const [year, mon] = month.split('-').map(Number)
  const total = year * 12 + (mon - 1) - n
  const y = Math.floor(total / 12)
  const m = (total % 12) + 1
  return `${y}-${String(m).padStart(2, '0')}-01`
}

// Income, expense, and discretionary-expense totals for the month up to and
// including `throughDate`. Discretionary = expenses with no recurring_runs
// row (i.e. entered by hand, not generated by a recurring rule).
async function actualsToDate(pool, month, throughDate) {
  const { start } = monthRange(month)
  const [rows] = await pool.query(
    `SELECT
       COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount END), 0) AS income,
       COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount END), 0) AS expense,
       COALESCE(SUM(CASE WHEN t.type = 'expense' AND rr.transaction_id IS NULL THEN t.amount END), 0) AS discretionary
     FROM transactions t
     LEFT JOIN recurring_runs rr ON rr.transaction_id = t.id
     WHERE t.deleted_at IS NULL AND t.type IN ('income', 'expense')
       AND t.txn_date >= ? AND t.txn_date <= ?`,
    [start, throughDate],
  )
  const r = rows[0]
  return { income: Number(r.income), expense: Number(r.expense), discretionary: Number(r.discretionary) }
}

// Per category: current-month spend up to `throughDate`, and total spend over
// the `monthsBack` calendar months before the current month (for averaging).
async function categoryHistory(pool, month, throughDate, monthsBack) {
  const { start } = monthRange(month)
  const prevStart = monthStartBefore(month, monthsBack)
  const [rows] = await pool.query(
    `SELECT c.id AS category_id, c.name,
       COALESCE(SUM(CASE WHEN t.txn_date >= ? AND t.txn_date <= ? THEN t.amount END), 0) AS current_spent,
       COALESCE(SUM(CASE WHEN t.txn_date >= ? AND t.txn_date < ? THEN t.amount END), 0) AS prev_total
     FROM categories c
     LEFT JOIN transactions t
       ON t.category_id = c.id AND t.type = 'expense' AND t.deleted_at IS NULL
     WHERE c.deleted_at IS NULL
     GROUP BY c.id, c.name`,
    [start, throughDate, prevStart, start],
  )
  return rows
}

// Pairs of non-deleted expenses in the month sharing amount + category and
// created within `withinHours` of each other — likely accidental double entry.
async function duplicateCandidates(pool, month, withinHours) {
  const { start, end } = monthRange(month)
  const [rows] = await pool.query(
    `SELECT t1.id AS id1, t2.id AS id2, t1.amount, t1.note, t1.txn_date, c.name AS category_name
     FROM transactions t1
     JOIN transactions t2
       ON t1.amount = t2.amount AND t1.category_id = t2.category_id AND t1.id < t2.id
       AND ABS(TIMESTAMPDIFF(HOUR, t1.created_at, t2.created_at)) <= ?
     LEFT JOIN categories c ON c.id = t1.category_id
     WHERE t1.type = 'expense' AND t2.type = 'expense'
       AND t1.deleted_at IS NULL AND t2.deleted_at IS NULL
       AND t1.txn_date >= ? AND t1.txn_date < ?`,
    [withinHours, start, end],
  )
  return rows
}

// Per category: this month's total, last month's total, and the total over
// the trailing `monthsBack` months (for a trailing average).
async function categoryComparison(pool, month, monthsBack) {
  const { start, end } = monthRange(month)
  const lastStart = monthStartBefore(month, 1)
  const prevStart = monthStartBefore(month, monthsBack)
  const [rows] = await pool.query(
    `SELECT c.id AS category_id, c.name,
       COALESCE(SUM(CASE WHEN t.txn_date >= ? AND t.txn_date < ? THEN t.amount END), 0) AS current_total,
       COALESCE(SUM(CASE WHEN t.txn_date >= ? AND t.txn_date < ? THEN t.amount END), 0) AS last_total,
       COALESCE(SUM(CASE WHEN t.txn_date >= ? AND t.txn_date < ? THEN t.amount END), 0) AS prev_total
     FROM categories c
     LEFT JOIN transactions t
       ON t.category_id = c.id AND t.type = 'expense' AND t.deleted_at IS NULL
     WHERE c.deleted_at IS NULL
     GROUP BY c.id, c.name`,
    [start, end, lastStart, start, prevStart, start],
  )
  return rows
}

// Per active budget: its limit, category name, and month-to-date spend
// (up to `throughDate`) — for the budget-burn anomaly.
async function budgetStatus(pool, month, throughDate) {
  const { start } = monthRange(month)
  const [rows] = await pool.query(
    `SELECT b.category_id, c.name, b.limit_amount AS \`limit\`,
       COALESCE(SUM(t.amount), 0) AS spent
     FROM budgets b
     JOIN categories c ON c.id = b.category_id
     LEFT JOIN transactions t
       ON t.category_id = b.category_id AND t.type = 'expense' AND t.deleted_at IS NULL
       AND t.txn_date >= ? AND t.txn_date <= ?
     WHERE b.deleted_at IS NULL
     GROUP BY b.category_id, c.name, b.limit_amount`,
    [start, throughDate],
  )
  return rows
}

module.exports = {
  actualsToDate,
  categoryHistory,
  duplicateCandidates,
  categoryComparison,
  budgetStatus,
  monthStartBefore,
}
